name: putra_mate
description: PutraMate - UPM mental wellness system (Flutter + Firebase)
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.2
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.6
  intl: ^0.20.2
  google_generative_ai: ^0.4.0
  http: ^1.2.0
  url_launcher: ^6.3.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/PutraMate.png
    - assets/images/upmbg.jpg
